[package]
name = "google-dino"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.7"
mairs = "0.1.5"
rand = "0.8.5"
thread = "0.1.0"
time = "0.3.23"
yaml-rust = "0.4.5"
